apiVersion: v1
kind: Service
metadata:
  name: poc-test-api
spec:
  type: NodePort
#   type: ClusterIP
  selector:
    app: poc-test-api
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30526
      targetPort: 8080